### ISSUE TITLE
Ignore ApplicationException, Could not decrypt methods

### ISSUE THREAD

**Issue by rootwangcheng** [Tianjiao/de4dot#11]
[vv.log](https://github.com/Tianjiao/de4dot/files/2684335/vv.log)

**Comment by Tianjiao** [comment]
Hello,
I can't see the TimeDateStamp of the Runtime DLL in the log, which to confirm the version of MaxtoCode.
Could you copy the MaxtoCode's Runtime DLL into the directory of the obfuscated assembly, then run "de4dot -vv" again?
