### ISSUE TITLE
WARNING: Ignore ApplicationException, Could not decrypt methods.

### ISSUE THREAD

**Issue by ccneusoft** [Tianjiao/de4dot#12]
D:\vstest\de4dot-master\Debug\net472>de4dot D:\vstest\input\ZnxxZxycfxt.exe

de4dot v3.1.41592.3405 Copyright (C) 2011-2015 de4dot@gmail.com
Latest version and source code: https://github.com/0xd4d/de4dot

== MaxtoCode (3.79sp1) - (3.87) Partial Fix by Tianjiao ==
Source code: https://github.com/Tianjiao/de4dot

More than one obfuscator detected:
  Dotfuscator 1032:1:0:4.10.2.2252 (use: -p df)
  MaxtoCode (use: -p mc)
Detected MaxtoCode (D:\vstest\input\ZnxxZxycfxt.exe)
Cleaning D:\vstest\input\ZnxxZxycfxt.exe
WARNING: Ignore ApplicationException, Could not decrypt methods.
Renaming all obfuscated symbols
Saving D:\vstest\input\ZnxxZxycfxt-cleaned.exe

**Comment by ccneusoft** [comment]
[znxxzxycfxt.zip](https://github.com/Tianjiao/de4dot/files/2708484/znxxzxycfxt.zip)

**Comment by Tianjiao** [comment]
您好！
日志文件显示，您的目标使用的是3.83版的MaxtoCode。
对于这个版本，目前仅支持字符串解密，及反混淆功能。
此外，日志文件显示，你的目标还使用了Dotfuscator进行了加壳。
感谢您的支持，有什么问题欢迎进一步提出。

**Comment by ccneusoft** [comment]
感谢您的及时回复
