### ISSUE TITLE
解maxtocode新版本加密报错

### ISSUE THREAD

**Issue by xiaoyuer2019** [Tianjiao/de4dot#4]
WARNING: Ignore ApplicationException, Could not decrypt methods.
Renaming all obfuscated symbols

**Comment by Tianjiao** [comment]
你好，这是警告，而不是错误。
麻烦你用WinHex打开反混淆后的程序，查看一下解密后的用户字符串。
谢谢。

**Comment by xiaoyuer2019** [comment]
您好，我放看了反编译后的程序，只有方法名，方法里的内容都是空的。

**Comment by Tianjiao** [comment]
我的修改版针对解密用户字符串而设计。
解密方法体的问题，我在源码里用英文作了[注释](https://github.com/Tianjiao/de4dot/commit/818e2be97b90fafaa5c6453ad43b36377fac1fb7)。
我修改的de4dot是开源的，你也可以在我的源码基础上做二次开发。

**Comment by xiaoyuer2019** [comment]
明白了，谢谢，请问能否修改一个能解密方法体的？

**Comment by Tianjiao** [comment]
个人认为MaxtoCode对方法体的加密，从密码学理论上，是不可逆的。

原版de4dot对MC方法体的解密，并不完整。
我用WinHex查看过，在文件末端仍有加密部分。
用反编译器只是能看到反编译后的方法体，但是反编译器是不会显示加密部分的。

从技术上说，可以采用某种暴力攻击，但这种手法CTF是不予承认的。
所以理论上无解。

国内对MaxtoCode新版的脱壳，我核对了下，脱壳后用de4dot仍然检测出MaxtoCode的痕迹，而且资源部分有残留。我不认为那属于解密。

而用户字符串MC是密码加密，猜出密码就能解密。这是双向的，这才是真正意义上的解密。

**Comment by Tianjiao** [comment]
完美脱壳的，没听说。
脱壳脱得看得到方法体的，有但极少数人掌握，并且不愿公开。
公开解密用户字符串的，就我一家。

不过脱壳机通常有硬编码，MaxtoCode一旦更新后这个版本往往就失效了。

我还是认为，能够拿到自己手上的工具才有现实意义。
