### ISSUE TITLE
good tool，can it decompile the encrypted dll

### ISSUE THREAD

**Issue by zchking** [Tianjiao/de4dot#5]
Hi.as newbird I use dnspy to decompile and debug the EXE, it call the function from an encrypted dll.  
issue:
1. the dll use code  obfuscation
2. in the decompile dll code.  the function in dll show it only return null, but it really have return.
3. when debug into dll function，it can't see the running line，but I know it really running some code step by step.

will your tool help this?
need your help
thank you so much.

**Comment by Tianjiao** [comment]
Hi. 
My tool can help you to de-obfuscate the code first.
You also need some _binary analysis framework_ such as [angr](https://github.com/angr/angr).
